Allow HTTPS URLs for WP backend during config
imranhsayed/nextjs-headless-wordpress pull request #45
Opened 2021-01-05 00:27 UTC by jaydiablo

I was trying to use an https:// URL for my WP backend and I kept getting that "URL Is not valid" error.

Modified the regex to make the `s` in `https` optional, rather than the `p` in `http`. :)

2022-02-13 03:34 UTC, w3bdesign approved these changes

2022-02-13 15:25 UTC, gautam-jha requested changes

2022-02-13 15:25 UTC, gautam-jha commented on nxtwp
> +    regex='(https?)://[-A-Za-z0-9:0-9]'
This won't be working for someone who will try the same for `https`.

Instead try this `(http|https):\/\/[-A-Za-z0-9:0-9]`

for more help on regex writing try [regex101](https://regex101.com/)

2022-02-14 17:34 UTC, jaydiablo commented on nxtwp
> +    regex='(https?)://[-A-Za-z0-9:0-9]'
@gautam-jha thanks for the reply!

`(https|http)` and `(https?)` are functionally equivalent in regex:

![image](https://user-images.githubusercontent.com/136907/153915038-c878665f-a07f-4a28-8304-1ba70de942e0.png)

![image](https://user-images.githubusercontent.com/136907/153915075-7a465b48-a834-4ae5-ad3c-8ba5cbc6a0af.png)

and for http:

![image](https://user-images.githubusercontent.com/136907/153915144-88135b3b-6a9c-4109-a5f2-91890a46f86c.png)

![image](https://user-images.githubusercontent.com/136907/153915175-8b5093cb-dd2b-4f4b-8a7f-49e5d615e4ac.png)

So that's really a matter of preference. As for the other changes, my goal here was just to make this work with https URLs. As this regex is currently, it won't work for https:

![image](https://user-images.githubusercontent.com/136907/153915744-b3331d4c-246c-4263-9844-6147704312a4.png)

![image](https://user-images.githubusercontent.com/136907/153915768-b40414f1-bc82-4303-9fca-25a9c76a3dd3.png)

With my small change in place, I was able to get this to work with an https URL.  It's up to you all if you want to change the regex to be more restrictive on what is a valid URL or not (this can end up becoming a deep rabbit hole, as seen here: https://mathiasbynens.be/demo/url-regex )

I'd recommend keeping it simple though :)

2022-02-15 11:02 UTC, gautam-jha commented on nxtwp
> +    regex='(https?)://[-A-Za-z0-9:0-9]'
@jaydiablo Thanks for your expaination! It will be better if we don't complicate it.
`when (https|http) and (https?) are functionally equivalent in regex:`

2022-02-15 11:03 UTC, gautam-jha approved these changes

2022-10-15 07:19 UTC, imranhsayed approved these changes

2022-10-15 07:19 UTC, merged